### ISSUE TITLE
Cant connect to websocket using node ws

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/SoLiD#40]
var WebSocket = require('ws');

    process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

    var ws = new WebSocket('wss://databox.me/');

    ws.on('open', function open() {
      console.log('connected');
      ws.send('ping');
    });

    ws.on('close', function close() {
      console.log('disconnected');
    });

    ws.on('message', function message(data, flags) {
      console.log(data);
    });

Gives

    node test.js 

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: unexpected server response (403)
        at ClientRequest.response (/var/www/ld/test/node_modules/ws/lib/WebSocket.js:674:15)
        at ClientRequest.g (events.js:180:16)
        at ClientRequest.EventEmitter.emit (events.js:95:17)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
        at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
        at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
        at CleartextStream.read [as _read] (tls.js:511:12)
        at CleartextStream.Readable.read (_stream_readable.js:320:10)
        at EncryptedStream.write [as _write] (tls.js:366:25)
        at doWrite (_stream_writable.js:223:10)

Same issue on localhost.  I suspect this could be an issue with the node ws module.  Will investigate further.

**Comment by melvincarvalho** [comment]
Seems to work with older versions of ws (npm).  This may be a lead on other websocket related issues such as friefox. 

I drilled into the https request and options but could not see anything obvious in the handshake that caused a 403.

 I'll close this issue for now, and raise on project specific instances such as GOLD if it persists.
